---
title: "Abundance_Features"
author: "Mang Zhu"
date: "June 29, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
yeast_pme <- read.table("Data/yeast_locus.txt", header = F)
names(yeast_pme)=c("uniport","locus")

abd <- read.table("pme/pme.abd", header = T)
names(abd)=c("name","abd")

hits <- read.csv("bin/hitbin1.csv", header = T)

#cut-off for PME abundance proteins
n <- 20
abd_cutoff <- quantile(abd$abd, probs = 1 - n/100)
abd_cutoff

#abundance bin
abd_Hco <- abd[which(abd$abd>=abd_cutoff),]

#compare high abundance hits
assign("hits_abd", abd[abd[,1] %in% hits[,2],])
```

```{r}

myarr<-c("aa","abd","acc","diso","egg","ord","seq","ss8","len","tm","cmpl","cpla","gvy","tgo","avpfam","totpfam","auniconc","hl")
nums<-c(1,2)
for (mar in myarr) {
  j<-paste("*.",mar,sep="")
  k <- read.table( dir("pme/",pattern=j,full.names=T) ) 
  for (num in nums){
    if (num==1){bin="hits_abd"}
    if (num==2){bin="abd_Hco"}
    #if (num==3){bin="abd_H"}
    # if (num==4){bin="bin4"}
    i <- paste(mar,num,sep="")
        assign(i, k[k[,1] %in% get(bin)[,1],])
    #if (num==5){bin="pme"}
  }
}
```

```{r NAME DATA COLUMNS, echo=FALSE}
nums<-c(1,2)
for (num in nums) {
  i<-paste("diso",num,sep="")
  j<-get(i)
  names(j)=c("name","ndis","ntot","pdis","nrun","maxrun","n1","lpsd","lps","n2","pfmd","pfm","n3","rna","n4","morf","n5","psite","pst2","n6","hydo","n7","chg","n8","pos","n9","pos2","n10","neg","n11","netq","n12","plr","n13","plr2","n14","qar","n15","lark","n16","lit1","n17","qn","n18","yg","n19","frg","n20","pxg","n21","rgg","n22","ryg","n23","pipi","n24","pipa","n25","hbd","n26","hba","n27","pak","n28","pak2","n30","lin","n31","gpg","n32","mvfy","n33","lin2","n34","scd","n35","R","n36","H","n37","K","n38","D","n39","E","n40","S","n41","T","n42","N","n43","Q","n44","C","n45","U","n46","G","n47","P","n48","A","n49","V","n50","I","n51","L","n52","M","n53","F","n54","Y","n55","W","n56","X")
  assign(i,j)

  i<-paste("abd",num,sep="")
  j<-get(i)
  names(j)=c("name","abd")
  assign(i,j)

  i<-paste("ss8",num,sep="")
  j<-get(i)
  names(j)=c("name","alpha","threeten","pihelix","extended","beta","turn","bend","other","tot")
  assign(i,j)

  i<-paste("acc",num,sep="")
  j<-get(i)
  names(j)=c("name","core","expo","tot")
  assign(i,j)

  
  i<-paste("len",num,sep="")
  j<-get(i)
  names(j)=c("name","diso","len","per","num","max")
  assign(i,j)
  
  i <- paste("cmpl",num,sep = "")
  j<-get(i)
  names(j) <- c("name","subunit")
  assign(i,j)
  
  i <- paste("cpla",num,sep = "")
  j<-get(i)
  names(j) <- c("name","subunit")
  assign(i,j)
  
  i <- paste("gvy",num,sep = "")
  j<-get(i)
  names(j) <- c("name","gvy")
  assign(i,j)
  
  i <- paste("tgo",num,sep = "")
  j<-get(i)
  names(j) <- c("name","sections","residues_total")
  assign(i,j)
  
  i <- paste("avpfam",num,sep = "")
  j<-get(i)
  names(j) <- c("name","DOM_AVG_LEN")
  assign(i,j)
  
  i <- paste("totpfam",num,sep = "")
  j<-get(i)
  names(j) <- c("name","tpfam_aa","total_aa")
  assign(i,j)
  
  i <- paste("hl",num,sep = "")
  j<-get(i)
  names(j) <- c("name","yeast_name","halflife")
  assign(i,j)
}
```

```{r PLOT VARIABLES}
mycol=c("#7FBF26","#C9CACA","gray60")
mynam=c("ntSP","PME")
```

```{r PLOT, fig.width=8, fig.height=8, echo=FALSE}

par(oma=c(1,1,1,1),mar=c(2,3,1,1),mgp=c(2,1,0), mfrow=c(3,5))

boxplot(diso1$ntot,diso2$ntot,col=mycol,ylab="Seq Len",ylim=c(0,1500),names=mynam,outline=FALSE)
plen<-c(wilcox.test(diso1$ntot,diso2$ntot)$p.value)

boxplot(diso1$pdis,diso2$pdis,col=mycol,ylab="% Disorder",names=mynam,outline=FALSE)
pdiso<-c(wilcox.test(diso1$pdis,diso2$pdis)$p.value)

boxplot(len1$max/len1$len,len2$max/len2$len,col=mycol,ylab="Max Diso Len",ylim=c(0,0.5),names=mynam,outline=FALSE)
pmdiso<-c(wilcox.test(len1$max/len1$len,len2$max/len2$len)$p.value)

boxplot(diso1$hydo,diso2$hydo,col=mycol,ylab="% Hydro",ylim=c(20,60),names=mynam,outline=FALSE)
phydro<-c(wilcox.test(diso1$hydo,diso2$hydo)$p.value)

boxplot(diso1$plr,diso2$plr,col=mycol,ylab="% Polar",ylim=c(20,50),names=mynam,outline=FALSE)
pplr<-c(wilcox.test(diso1$plr,diso2$plr)$p.value)

boxplot(diso1$chg,diso2$chg,col=mycol,ylab="% Charged",ylim=c(5,45),names=mynam,outline=FALSE)
pchg<-c(wilcox.test(diso1$chg,diso2$chg)$p.value)

boxplot(diso1$pos2,diso2$pos2,col=mycol,ylab="% Positive",ylim=c(0,30),names=mynam,outline=FALSE)
ppos<-c(wilcox.test(diso1$pos2,diso2$pos2)$p.value)

boxplot(diso1$neg,diso2$neg,col=mycol,ylab="% Negative",ylim=c(0,30),names=mynam,outline=FALSE)
pneg<-c(wilcox.test(diso1$neg,diso2$neg)$p.value)

boxplot(diso1$pipi,diso2$pipi,col=mycol,ylab="% pi-pi",ylim=c(30,70),names=mynam,outline=FALSE)
ppipi<-c(wilcox.test(diso1$pipi,diso2$pipi)$p.value)

boxplot(diso1$hbd,diso2$hbd,col=mycol,ylab="% HB Donor",ylim=c(30,60),names=mynam,outline=FALSE)
phbd<-c(wilcox.test(diso1$hbd,diso2$hbd)$p.value)

boxplot(diso1$hba,diso2$hba,col=mycol,ylab="% HB Acc",ylim=c(30,60),names=mynam,outline=FALSE)
phba<-c(wilcox.test(diso1$hba,diso2$hba)$p.value)

boxplot((ss81$alpha+ss81$threeten+ss81$pihelix),(ss82$alpha+ss82$threeten+ss82$pihelix),col=mycol,ylab="% Helix",names=mynam,outline=FALSE)
phelix<-c(wilcox.test((ss81$alpha+ss81$threeten+ss81$pihelix),(ss82$alpha+ss82$threeten+ss82$pihelix))$p.value)

boxplot((ss81$extended+ss81$beta+ss81$turn),(ss82$extended+ss82$beta+ss82$turn),col=mycol,ylab="% Beta",names=mynam,outline=FALSE)
pbeta<-c(wilcox.test((ss81$extended+ss81$beta+ss81$turn),(ss82$extended+ss82$beta+ss82$turn))$p.value)

boxplot(ss81$other,ss82$other,col=mycol,ylab="% Coil",names=mynam,outline=FALSE)
pother<-c(wilcox.test(ss81$other,ss82$other)$p.value)

boxplot(acc1$expo,acc2$expo,col=mycol,names=mynam,outline=FALSE,ylab="% Sol Exp")
pexpo<-c(wilcox.test(acc1$expo,acc2$expo)$p.value)

#####

par(oma=c(1,1,1,1),mar=c(2,3,1,1),mgp=c(2,1,0), mfrow=c(3,5))
boxplot(abd1$abd,abd2$abd,col=mycol,names=mynam,outline=FALSE, ylab="Abnd [ppm]",ylim=c(0,1000))
pabd<-c(wilcox.test(abd1$abd,abd2$abd)$p.value)

boxplot(totpfam1$tpfam_aa/totpfam1$total_aa,totpfam2$tpfam_aa/totpfam2$total_aa,col=mycol,names=mynam,ylab="pfam size/length",outline=FALSE)
ptotpfama<-c(wilcox.test(totpfam1$tpfam_aa/totpfam1$total_aa,totpfam2$tpfam_aa/totpfam2$total_aa)$p.value)

boxplot(diso1$pfm/diso1$ntot,diso2$pfm/diso2$ntot,ylim=c(0,0.015),col=mycol,names=mynam,outline=FALSE,ylab="pfam/residue")
ppfm<-c(wilcox.test(diso1$pfm/diso1$ntot,diso2$pfm/diso2$ntot)$p.value)


boxplot(tm1$V3,tm2$V3,col=mycol,names=mynam,outline=FALSE,ylab="Tm")
ptm<-c(wilcox.test(tm1$V3,tm2$V3)$p.value)

boxplot(cmpl1$subunit,cmpl2$subunit,col=mycol,ylab="# of subunit (w/o mono)",names=mynam,outline=FALSE, sub = paste("hits n=",length(cmpl1$subunit),"non-hits n=",length(cmpl2$subunit)))
pcmpl<-c(wilcox.test(cmpl1$subunit,cmpl2$subunit)$p.value)

boxplot(cpla1$subunit,cpla2$subunit,col=mycol,ylab="# of subunit (w/ mono)",names=mynam,outline=FALSE, sub = paste("hits n=",length(cpla1$subunit),"non-hits n=",length(cpla2$subunit)))
pcpla<-c(wilcox.test(cpla1$subunit,cpla2$subunit)$p.value)

boxplot(gvy1$gvy,gvy2$gvy,col=mycol,names=mynam,outline=FALSE,ylab="GRAVY",ylim=c(-1.5,1))
pgvy<-c(wilcox.test(gvy1$gvy,gvy2$gvy)$p.value)

boxplot(tgo1$residues_total/diso1$ntot,tgo2$residues_total/diso2$ntot,col=mycol,names=mynam,ylab="# of tango residues/residue",ylim=c(0,0.4),outline=FALSE)
ptgorr<-c(wilcox.test(tgo1$residues_total/diso1$ntot,tgo2$residues_total/diso2$ntot)$p.value)

boxplot(hl1$halflife,hl2$halflife,col=mycol,ylab="Protein Halflife", names=mynam,outline=FALSE)
phl<-c(wilcox.test(hl1$halflife,hl2$halflife)$p.value)

```

```{r}
pCO <- 3.41E-11

myp<-rbind(plen,pdiso,pmdiso,phydro,pplr,pchg,ppos,pneg,ppipi,phbd,phba,phelix,pbeta,pother,pexpo,pabd,ptotpfama,ppfm,ptm,pcmpl,pgvy,ptgorr,phl,pCO)
myp

A1vA2<-p.adjust(myp[,1],method="hochberg")

mypc<-cbind(A1vA2)
mypc
```